config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rock_photos
  resources :rocks, except: [:show]
  resources :samples, except: [:show]
  resources :sample_photos, except: [:show]
  resources :structure_photos, except: [:show]
  resources :structures, except: [:show]
  resources :outcrops, except: [:show]
  resources :outcrop_photos, except: [:show]
  resources :stages, except: [:show]
  resources :rock_structure_associations, except: [:show]
  resources :projects, except: [:show]
  resources :users, except: [:show]

  delete 'projects', controller: 'projects', action: 'destroy'
  delete 'rocks', controller: 'rocks', action: 'destroy'
  delete 'samples', controller: 'samples', action: 'destroy'
  delete 'structures', controller: 'structures', action: 'destroy'
  delete 'stages', controller: 'stages', action: 'destroy'
  delete 'users', controller: 'users', action: 'destroy'
  delete 'outcrops', controller: 'outcrops', action: 'destroy'
  delete 'rock_structure_associations', controller: 'rock_structure_associations', action: 'destroy'


  delete 'outcrop_photos', controller: 'outcrop_photos', action: 'destroy'
  delete 'rock_photos', controller: 'rock_photos', action: 'destroy'
  delete 'sample_photos', controller: 'sample_photos', action: 'destroy'
  delete 'structure_photos', controller: 'structure_photos', action: 'destroy'

  get 'rock_photos/search/findById', controller: 'rock_photos', action: 'show'
  get 'rocks/search/findById', controller: 'rocks', action: 'show'
  get 'samples/search/findById', controller: 'samples', action: 'show'
  get 'sample_photos/search/findById', controller: 'sample_photos', action: 'show'
  get 'associations/search/findById', controller: 'rock_structure_associations', action: 'show'
  get 'structure_photos/search/findById', controller: 'structure_photos', action: 'show'
  get 'structures/search/findById', controller: 'structures', action: 'show'
  get 'outcrops/search/findById', controller: 'outcrops', action: 'show'
  get 'outcrop_photos/search/findById', controller: 'outcrop_photos', action: 'show'
  get 'stages/search/findById', controller: 'stages', action: 'show'
  get 'projects/search/findById', controller: 'projects', action: 'show'
  get 'users/search/findFirstByEmail', controller: 'users', action: 'show'
  get 'users/:id', controller: 'users', action: 'show_by_id'


  get 'outcrops/user_outcrops', controller: 'outcrops', action: 'user_outcrops'

  get 'rock_structure_associations/find_rock_structure_associations', controller: 'rock_structure_associations', action: 'find_rock_structure_associations'
  post 'rock_structure_associations/delete_rock_structure_association_by_rock', controller: 'rock_structure_associations', action:'delete_rock_structure_association_by_rock'

  get 'outcrop/:id/outcrop_photos', controller: 'outcrop_photos', action: 'list'
  get 'rock/:id/rock_photos', controller: 'rock_photos', action: 'list'
  get 'sample/:id/sample_photos', controller: 'sample_photos', action: 'list'
  get 'structure/:id/structure_photos', controller: 'structure_photos', action: 'list'

  post 'outcropPhotos', controller: 'outcrop_photos', action:'create'
  put 'outcropPhotos', controller: 'outcrop_photos', action:'update'
  post 'samplePhotos', controller: 'sample_photos', action:'create'
  put 'samplePhotos', controller: 'sample_photos', action:'update'
  post 'rockPhotos', controller: 'rock_photos', action:'create'
  put 'rockPhotos', controller: 'rock_photos', action:'update'
  post 'structurePhotos', controller: 'structure_photos', action:'create'
  put 'structurePhotos', controller: 'structure_photos', action:'update'

  post 'users/login', controller: 'users', action: 'login'

  put 'associations', controller: 'rock_structure_associations', action:'update'
  post 'associations', controller: 'rock_structure_associations', action:'create'
  get 'associations', controller: 'rock_structure_associations', action:'destroy'


  get 'statistics/photos_list',controller: 'statistics', action: 'photos_list'
  get 'statistics/sizes',controller: 'statistics', action: 'sizes'
  get 'statistics/altitudes', controller: 'statistics', action: 'altitudes'
  get 'statistics/stages_by_uf', controller: 'statistics', action: 'stages_by_uf'

  get 'projects/get_all_project_data', controller: 'projects', action: 'get_all_project_data'
end

app/models/structure.rb
class Structure < ApplicationRecord
  self.primary_key = 'uuid'
  belongs_to :outcrop
  has_many :rock_structure_associations, dependent: :destroy
  has_many :structure_photos, dependent: :destroy
  validates_presence_of :description, :unless => lambda {self.structure_type == 1}
  validates_presence_of :dip_direction, :unless => lambda {self.structure_type == 0}
  validates_presence_of :dip, :unless => lambda {self.structure_type == 0}
  validates_presence_of :name, :unless => lambda {self.structure_type == 0}
  validates_presence_of :outcrop_id

  before_create do
    self.persisted_time = DateTime.now.strftime('%Q')
  end

  before_create :generate_token

  protected

  def generate_token
    if self.uuid.nil?
      self.uuid = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Structure.exists?(uuid: random_token)
      end
    end
  end
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :verify_auth_header
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  before_action :underscore_params!

  skip_before_filter :verify_authenticity_token

  def underscore_params!
    underscore_hash = -> (hash) do
      hash.transform_keys!(&:underscore)
      hash.each do |key, value|
        if value.is_a?(ActionController::Parameters)
          underscore_hash.call(value)
        elsif value.is_a?(Array)
          value.each do |item|
            next unless item.is_a?(ActionController::Parameters)
            underscore_hash.call(item)
          end
        end
      end
    end
    underscore_hash.call(params)
  end


  # GET /structures
  # GET /structures.json
  def index
    if params[:outcrop_id]
      @structures = Structure.where(outcrop_id: params[:outcrop_id])
                        .paginate(page: params[:page], per_page: params[:size])
                        .order(created_at: :desc).all
      render json: @structures
    else
      @structures = Structure.paginate(page: params[:page], per_page: params[:size])
                        .order(created_at: :desc).all
      render json: @structures
    end
  end

  # GET /structures/1
  # GET /structures/1.json
  def show
    render json: @structure
  end

  # GET /structures/new
  def new
    @structure = Structure.new
  end

  # GET /structures/1/edit
  def edit
  end

  # POST /structures
  # POST /structures.json
  def create
    @structure = Structure.new(structure_params)

    if @structure.save
      render json: @structure, status: :created, location: @structure
    else
      render json: @structure.errors, status: :unprocessable_entity
    end

  end

  # PATCH/PUT /structures/1
  # PATCH/PUT /structures/1.json
  def update
    if params[:updated_at].present?
      return render json: @structure, status: :ok if params[:updated_at].to_datetime < @structure.updated_at
    end

    if @structure.update(structure_params)
      render json: @structure, status: :ok
    else
      render json: @structure.errors, status: :unprocessable_entity
    end

  end

  # DELETE /structures/1
  # DELETE /structures/1.json
  def destroy
    @structure.destroy
    render json: {message: 'Estrutura Excluida'}, status: :ok
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_structure
    @structure = Structure.find(params[:uuid])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def structure_params
    params.permit(:uuid, :description, :dip, :dip_direction, :name, :phase, :structure_type, :outcrop_id, :deleted_at, :updated_at)
  end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/_form.html.erb
<%= form_for(structure) do |f| %>
  <% if structure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(structure.errors.count, "error") %> prohibited this structure from being saved:</h2>

      <ul>
      <% structure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :dip %>
    <%= f.text_field :dip %>
  </div>

  <div class="field">
    <%= f.label :dip_direction %>
    <%= f.text_field :dip_direction %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phase %>
    <%= f.text_field :phase %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :outcrop_uuid %>
    <%= f.text_field :outcrop_uuid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/structures/edit.html.erb
<h1>Editing Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Show', @structure %> |
<%= link_to 'Back', structures_path %>

app/views/structures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Structures</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Description</th>
      <th>Dip</th>
      <th>Dip direction</th>
      <th>Name</th>
      <th>Phase</th>
      <th>Type</th>
      <th>Outcrop uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @structures.each do |structure| %>
      <tr>
        <td><%= structure.uuid %></td>
        <td><%= structure.description %></td>
        <td><%= structure.dip %></td>
        <td><%= structure.dip_direction %></td>
        <td><%= structure.name %></td>
        <td><%= structure.phase %></td>
        <td><%= structure.type %></td>
        <td><%= structure.outcrop_uuid %></td>
        <td><%= link_to 'Show', structure %></td>
        <td><%= link_to 'Edit', edit_structure_path(structure) %></td>
        <td><%= link_to 'Destroy', structure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Structure', new_structure_path %>

app/views/structures/new.html.erb
<h1>New Structure</h1>

<%= render 'form', structure: @structure %>

<%= link_to 'Back', structures_path %>