config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rock_photos
  resources :rocks, except: [:show]
  resources :samples, except: [:show]
  resources :sample_photos, except: [:show]
  resources :structure_photos, except: [:show]
  resources :structures, except: [:show]
  resources :outcrops, except: [:show]
  resources :outcrop_photos, except: [:show]
  resources :stages, except: [:show]
  resources :rock_structure_associations, except: [:show]
  resources :projects, except: [:show]
  resources :users, except: [:show]

  delete 'projects', controller: 'projects', action: 'destroy'
  delete 'rocks', controller: 'rocks', action: 'destroy'
  delete 'samples', controller: 'samples', action: 'destroy'
  delete 'structures', controller: 'structures', action: 'destroy'
  delete 'stages', controller: 'stages', action: 'destroy'
  delete 'users', controller: 'users', action: 'destroy'
  delete 'outcrops', controller: 'outcrops', action: 'destroy'
  delete 'rock_structure_associations', controller: 'rock_structure_associations', action: 'destroy'


  delete 'outcrop_photos', controller: 'outcrop_photos', action: 'destroy'
  delete 'rock_photos', controller: 'rock_photos', action: 'destroy'
  delete 'sample_photos', controller: 'sample_photos', action: 'destroy'
  delete 'structure_photos', controller: 'structure_photos', action: 'destroy'

  get 'rock_photos/search/findById', controller: 'rock_photos', action: 'show'
  get 'rocks/search/findById', controller: 'rocks', action: 'show'
  get 'samples/search/findById', controller: 'samples', action: 'show'
  get 'sample_photos/search/findById', controller: 'sample_photos', action: 'show'
  get 'associations/search/findById', controller: 'rock_structure_associations', action: 'show'
  get 'structure_photos/search/findById', controller: 'structure_photos', action: 'show'
  get 'structures/search/findById', controller: 'structures', action: 'show'
  get 'outcrops/search/findById', controller: 'outcrops', action: 'show'
  get 'outcrop_photos/search/findById', controller: 'outcrop_photos', action: 'show'
  get 'stages/search/findById', controller: 'stages', action: 'show'
  get 'projects/search/findById', controller: 'projects', action: 'show'
  get 'users/search/findFirstByEmail', controller: 'users', action: 'show'
  get 'users/:id', controller: 'users', action: 'show_by_id'


  get 'outcrops/user_outcrops', controller: 'outcrops', action: 'user_outcrops'

  get 'rock_structure_associations/find_rock_structure_associations', controller: 'rock_structure_associations', action: 'find_rock_structure_associations'
  post 'rock_structure_associations/delete_rock_structure_association_by_rock', controller: 'rock_structure_associations', action:'delete_rock_structure_association_by_rock'

  get 'outcrop/:id/outcrop_photos', controller: 'outcrop_photos', action: 'list'
  get 'rock/:id/rock_photos', controller: 'rock_photos', action: 'list'
  get 'sample/:id/sample_photos', controller: 'sample_photos', action: 'list'
  get 'structure/:id/structure_photos', controller: 'structure_photos', action: 'list'

  post 'outcropPhotos', controller: 'outcrop_photos', action:'create'
  put 'outcropPhotos', controller: 'outcrop_photos', action:'update'
  post 'samplePhotos', controller: 'sample_photos', action:'create'
  put 'samplePhotos', controller: 'sample_photos', action:'update'
  post 'rockPhotos', controller: 'rock_photos', action:'create'
  put 'rockPhotos', controller: 'rock_photos', action:'update'
  post 'structurePhotos', controller: 'structure_photos', action:'create'
  put 'structurePhotos', controller: 'structure_photos', action:'update'

  post 'users/login', controller: 'users', action: 'login'

  put 'associations', controller: 'rock_structure_associations', action:'update'
  post 'associations', controller: 'rock_structure_associations', action:'create'
  get 'associations', controller: 'rock_structure_associations', action:'destroy'


  get 'statistics/photos_list',controller: 'statistics', action: 'photos_list'
  get 'statistics/sizes',controller: 'statistics', action: 'sizes'
  get 'statistics/altitudes', controller: 'statistics', action: 'altitudes'
  get 'statistics/stages_by_uf', controller: 'statistics', action: 'stages_by_uf'

  get 'projects/get_all_project_data', controller: 'projects', action: 'get_all_project_data'
end

app/models/rock_structure_association.rb
class RockStructureAssociation < ApplicationRecord
  self.primary_key = 'uuid'
  belongs_to :outcrop
  belongs_to :rock
  belongs_to :structure

  before_create do
    self.persisted_time = DateTime.now.strftime('%Q')
  end

  before_create :generate_token

  protected

  def generate_token
    if self.uuid.nil?
      self.uuid = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless RockStructureAssociation.exists?(uuid: random_token)
      end
    end
  end
end

app/controllers/rock_structure_associations_controller.rb
class RockStructureAssociationsController < ApplicationController
  before_action :verify_auth_header
  before_action :set_rock_structure_association, only: [:show, :edit, :update, :destroy]

  before_action :underscore_params!

  skip_before_filter :verify_authenticity_token

  def underscore_params!
    underscore_hash = -> (hash) do
      hash.transform_keys!(&:underscore)
      hash.each do |key, value|
        if value.is_a?(ActionController::Parameters)
          underscore_hash.call(value)
        elsif value.is_a?(Array)
          value.each do |item|
            next unless item.is_a?(ActionController::Parameters)
            underscore_hash.call(item)
          end
        end
      end
    end
    underscore_hash.call(params)
  end

  # GET /rock_structure_associations
  # GET /rock_structure_associations.json
  def index
    @rock_structure_associations = RockStructureAssociation.paginate(page: params[:page], per_page: params[:size])
    .order(created_at: :desc).all
    render json: @rock_structure_associations
  end

  def find_rock_structure_associations
    @rock_structure_associations = Structure.joins("INNER JOIN rock_structure_associations ON structures.uuid = rock_structure_associations.structure_id where rock_structure_associations.rock_id = '#{params[:rock_id]}' and rock_structure_associations.outcrop_id = '#{params[:outcrop_id]}'")
    render json: @rock_structure_associations
  end

  # GET /rock_structure_associations/1
  # GET /rock_structure_associations/1.json
  def show
    render json: @rock_structure_association
  end

  # GET /rock_structure_associations/new
  def new
    @rock_structure_association = RockStructureAssociation.new
  end

  # GET /rock_structure_associations/1/edit
  def edit
  end

  # POST /rock_structure_associations
  # POST /rock_structure_associations.json
  def create
    @rock_structure_association = RockStructureAssociation.new(rock_structure_association_params)

      if @rock_structure_association.save
        render json:@rock_structure_association, status: :created
      else
        render json: @rock_structure_association.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /rock_structure_associations/1
  # PATCH/PUT /rock_structure_associations/1.json
  def update
      if @rock_structure_association.update(rock_structure_association_params)
        render json: @rock_structure_association, status: :ok, location: @rock_structure_association
      else
        render json: @rock_structure_association.errors, status: :unprocessable_entity
      end
  end

  def delete_rock_structure_association_by_rock
    @rock_structure_association = RockStructureAssociation.where("rock_structure_associations.rock_id = '#{params[:rock_id]}' and rock_structure_associations.structure_id = '#{params[:structure_id]}' and rock_structure_associations.outcrop_id = '#{params[:outcrop_id]}'").take
    if @rock_structure_association.destroy
      render json: {message: 'Associação Excluida'} , status: :ok
    else
      render json: @rock_structure_association.errors, status: :unprocessable_entity
    end
  end

  # DELETE /rock_structure_associations/1
  # DELETE /rock_structure_associations/1.json
  def destroy
    @rock_structure_association.destroy
    render json: {message: 'Associação Excluida'} , status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rock_structure_association
      @rock_structure_association = RockStructureAssociation.find(params[:uuid])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rock_structure_association_params
      params.permit(:uuid, :structure_id, :rock_id, :outcrop_id,:deleted_at)
    end
end

app/helpers/rock_structure_associations_helper.rb
module RockStructureAssociationsHelper
end

app/views/rock_structure_associations/_form.html.erb
<%= form_for(rock_structure_association) do |f| %>
  <% if rock_structure_association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rock_structure_association.errors.count, "error") %> prohibited this rock_structure_association from being saved:</h2>

      <ul>
      <% rock_structure_association.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :structure_uuid %>
    <%= f.text_field :structure_uuid %>
  </div>

  <div class="field">
    <%= f.label :rock_uuid %>
    <%= f.text_field :rock_uuid %>
  </div>

  <div class="field">
    <%= f.label :outcrop_uuid %>
    <%= f.text_field :outcrop_uuid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rock_structure_associations/edit.html.erb
<h1>Editing Rock Structure Association</h1>

<%= render 'form', rock_structure_association: @rock_structure_association %>

<%= link_to 'Show', @rock_structure_association %> |
<%= link_to 'Back', rock_structure_associations_path %>

app/views/rock_structure_associations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rock Structure Associations</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Structure uuid</th>
      <th>Rock uuid</th>
      <th>Outcrop uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rock_structure_associations.each do |rock_structure_association| %>
      <tr>
        <td><%= rock_structure_association.uuid %></td>
        <td><%= rock_structure_association.structure_uuid %></td>
        <td><%= rock_structure_association.rock_uuid %></td>
        <td><%= rock_structure_association.outcrop_uuid %></td>
        <td><%= link_to 'Show', rock_structure_association %></td>
        <td><%= link_to 'Edit', edit_rock_structure_association_path(rock_structure_association) %></td>
        <td><%= link_to 'Destroy', rock_structure_association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rock Structure Association', new_rock_structure_association_path %>

app/views/rock_structure_associations/new.html.erb
<h1>New Rock Structure Association</h1>

<%= render 'form', rock_structure_association: @rock_structure_association %>

<%= link_to 'Back', rock_structure_associations_path %>