config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rock_photos
  resources :rocks, except: [:show]
  resources :samples, except: [:show]
  resources :sample_photos, except: [:show]
  resources :structure_photos, except: [:show]
  resources :structures, except: [:show]
  resources :outcrops, except: [:show]
  resources :outcrop_photos, except: [:show]
  resources :stages, except: [:show]
  resources :rock_structure_associations, except: [:show]
  resources :projects, except: [:show]
  resources :users, except: [:show]

  delete 'projects', controller: 'projects', action: 'destroy'
  delete 'rocks', controller: 'rocks', action: 'destroy'
  delete 'samples', controller: 'samples', action: 'destroy'
  delete 'structures', controller: 'structures', action: 'destroy'
  delete 'stages', controller: 'stages', action: 'destroy'
  delete 'users', controller: 'users', action: 'destroy'
  delete 'outcrops', controller: 'outcrops', action: 'destroy'
  delete 'rock_structure_associations', controller: 'rock_structure_associations', action: 'destroy'


  delete 'outcrop_photos', controller: 'outcrop_photos', action: 'destroy'
  delete 'rock_photos', controller: 'rock_photos', action: 'destroy'
  delete 'sample_photos', controller: 'sample_photos', action: 'destroy'
  delete 'structure_photos', controller: 'structure_photos', action: 'destroy'

  get 'rock_photos/search/findById', controller: 'rock_photos', action: 'show'
  get 'rocks/search/findById', controller: 'rocks', action: 'show'
  get 'samples/search/findById', controller: 'samples', action: 'show'
  get 'sample_photos/search/findById', controller: 'sample_photos', action: 'show'
  get 'associations/search/findById', controller: 'rock_structure_associations', action: 'show'
  get 'structure_photos/search/findById', controller: 'structure_photos', action: 'show'
  get 'structures/search/findById', controller: 'structures', action: 'show'
  get 'outcrops/search/findById', controller: 'outcrops', action: 'show'
  get 'outcrop_photos/search/findById', controller: 'outcrop_photos', action: 'show'
  get 'stages/search/findById', controller: 'stages', action: 'show'
  get 'projects/search/findById', controller: 'projects', action: 'show'
  get 'users/search/findFirstByEmail', controller: 'users', action: 'show'
  get 'users/:id', controller: 'users', action: 'show_by_id'


  get 'outcrops/user_outcrops', controller: 'outcrops', action: 'user_outcrops'

  get 'rock_structure_associations/find_rock_structure_associations', controller: 'rock_structure_associations', action: 'find_rock_structure_associations'
  post 'rock_structure_associations/delete_rock_structure_association_by_rock', controller: 'rock_structure_associations', action:'delete_rock_structure_association_by_rock'

  get 'outcrop/:id/outcrop_photos', controller: 'outcrop_photos', action: 'list'
  get 'rock/:id/rock_photos', controller: 'rock_photos', action: 'list'
  get 'sample/:id/sample_photos', controller: 'sample_photos', action: 'list'
  get 'structure/:id/structure_photos', controller: 'structure_photos', action: 'list'

  post 'outcropPhotos', controller: 'outcrop_photos', action:'create'
  put 'outcropPhotos', controller: 'outcrop_photos', action:'update'
  post 'samplePhotos', controller: 'sample_photos', action:'create'
  put 'samplePhotos', controller: 'sample_photos', action:'update'
  post 'rockPhotos', controller: 'rock_photos', action:'create'
  put 'rockPhotos', controller: 'rock_photos', action:'update'
  post 'structurePhotos', controller: 'structure_photos', action:'create'
  put 'structurePhotos', controller: 'structure_photos', action:'update'

  post 'users/login', controller: 'users', action: 'login'

  put 'associations', controller: 'rock_structure_associations', action:'update'
  post 'associations', controller: 'rock_structure_associations', action:'create'
  get 'associations', controller: 'rock_structure_associations', action:'destroy'


  get 'statistics/photos_list',controller: 'statistics', action: 'photos_list'
  get 'statistics/sizes',controller: 'statistics', action: 'sizes'
  get 'statistics/altitudes', controller: 'statistics', action: 'altitudes'
  get 'statistics/stages_by_uf', controller: 'statistics', action: 'stages_by_uf'

  get 'projects/get_all_project_data', controller: 'projects', action: 'get_all_project_data'
end

app/models/stage.rb
class Stage < ApplicationRecord
  self.primary_key = 'uuid'
  has_many :outcrops, dependent: :destroy
  belongs_to :project

  before_create :generate_token

  validates_presence_of :name
  validates_presence_of :initial_date
  validates_presence_of :project_id

  before_create do
    self.persisted_time = DateTime.now.strftime('%Q')
  end

  protected

  def generate_token
    if self.uuid.nil?
      self.uuid = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Stage.exists?(uuid: random_token)
      end
    end
  end

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :verify_auth_header
  before_action :set_stage, only: [:show, :edit, :update, :destroy]

  before_action :underscore_params!

  skip_before_filter :verify_authenticity_token

  def underscore_params!
    underscore_hash = -> (hash) do
      hash.transform_keys!(&:underscore)
      hash.each do |key, value|
        if value.is_a?(ActionController::Parameters)
          underscore_hash.call(value)
        elsif value.is_a?(Array)
          value.each do |item|
            next unless item.is_a?(ActionController::Parameters)
            underscore_hash.call(item)
          end
        end
      end
    end
    underscore_hash.call(params)
  end

  # GET /stages
  # GET /stages.json
  def index
    if params[:project_id]
      @stages = Stage.where(project_id: params[:project_id])
                    .paginate(page: params[:page], per_page: params[:size])
                    .order(created_at: :desc).all
      render json: @stages
    else
      @stages = Stage.paginate(page: params[:page], per_page: params[:size])
                    .order(created_at: :desc).all
      render json: @stages
    end
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
    render json: @stage
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    if @stage.save
      render json: @stage, status: :created
    else
      render json: @stage.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    if params[:updated_at].present?
      return render json: @stage, status: :ok if params[:updated_at].to_datetime < @stage.updated_at
    end

    if @stage.update(stage_params)
      render json: @stage, status: :ok
    else
      render json: @stage.errors, status: :unprocessable_entity
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    render json: {message: 'Etapa Excluida'}, status: :ok
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stage
    @stage = Stage.find(params[:uuid])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stage_params
    params.permit(:uuid, :city, :initialDate, :initial_date, :name, :uf, :project_id, :deleted_at, :updated_at)
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(stage) do |f| %>
  <% if stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% stage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :initial_date %>
    <%= f.text_field :initial_date %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :uf %>
    <%= f.text_field :uf %>
  </div>

  <div class="field">
    <%= f.label :project_uuid %>
    <%= f.text_field :project_uuid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stages</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>City</th>
      <th>Initial date</th>
      <th>Name</th>
      <th>Uf</th>
      <th>Project uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.uuid %></td>
        <td><%= stage.city %></td>
        <td><%= stage.initial_date %></td>
        <td><%= stage.name %></td>
        <td><%= stage.uf %></td>
        <td><%= stage.project_uuid %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Back', stages_path %>