config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rock_photos
  resources :rocks, except: [:show]
  resources :samples, except: [:show]
  resources :sample_photos, except: [:show]
  resources :structure_photos, except: [:show]
  resources :structures, except: [:show]
  resources :outcrops, except: [:show]
  resources :outcrop_photos, except: [:show]
  resources :stages, except: [:show]
  resources :rock_structure_associations, except: [:show]
  resources :projects, except: [:show]
  resources :users, except: [:show]

  delete 'projects', controller: 'projects', action: 'destroy'
  delete 'rocks', controller: 'rocks', action: 'destroy'
  delete 'samples', controller: 'samples', action: 'destroy'
  delete 'structures', controller: 'structures', action: 'destroy'
  delete 'stages', controller: 'stages', action: 'destroy'
  delete 'users', controller: 'users', action: 'destroy'
  delete 'outcrops', controller: 'outcrops', action: 'destroy'
  delete 'rock_structure_associations', controller: 'rock_structure_associations', action: 'destroy'


  delete 'outcrop_photos', controller: 'outcrop_photos', action: 'destroy'
  delete 'rock_photos', controller: 'rock_photos', action: 'destroy'
  delete 'sample_photos', controller: 'sample_photos', action: 'destroy'
  delete 'structure_photos', controller: 'structure_photos', action: 'destroy'

  get 'rock_photos/search/findById', controller: 'rock_photos', action: 'show'
  get 'rocks/search/findById', controller: 'rocks', action: 'show'
  get 'samples/search/findById', controller: 'samples', action: 'show'
  get 'sample_photos/search/findById', controller: 'sample_photos', action: 'show'
  get 'associations/search/findById', controller: 'rock_structure_associations', action: 'show'
  get 'structure_photos/search/findById', controller: 'structure_photos', action: 'show'
  get 'structures/search/findById', controller: 'structures', action: 'show'
  get 'outcrops/search/findById', controller: 'outcrops', action: 'show'
  get 'outcrop_photos/search/findById', controller: 'outcrop_photos', action: 'show'
  get 'stages/search/findById', controller: 'stages', action: 'show'
  get 'projects/search/findById', controller: 'projects', action: 'show'
  get 'users/search/findFirstByEmail', controller: 'users', action: 'show'
  get 'users/:id', controller: 'users', action: 'show_by_id'


  get 'outcrops/user_outcrops', controller: 'outcrops', action: 'user_outcrops'

  get 'rock_structure_associations/find_rock_structure_associations', controller: 'rock_structure_associations', action: 'find_rock_structure_associations'
  post 'rock_structure_associations/delete_rock_structure_association_by_rock', controller: 'rock_structure_associations', action:'delete_rock_structure_association_by_rock'

  get 'outcrop/:id/outcrop_photos', controller: 'outcrop_photos', action: 'list'
  get 'rock/:id/rock_photos', controller: 'rock_photos', action: 'list'
  get 'sample/:id/sample_photos', controller: 'sample_photos', action: 'list'
  get 'structure/:id/structure_photos', controller: 'structure_photos', action: 'list'

  post 'outcropPhotos', controller: 'outcrop_photos', action:'create'
  put 'outcropPhotos', controller: 'outcrop_photos', action:'update'
  post 'samplePhotos', controller: 'sample_photos', action:'create'
  put 'samplePhotos', controller: 'sample_photos', action:'update'
  post 'rockPhotos', controller: 'rock_photos', action:'create'
  put 'rockPhotos', controller: 'rock_photos', action:'update'
  post 'structurePhotos', controller: 'structure_photos', action:'create'
  put 'structurePhotos', controller: 'structure_photos', action:'update'

  post 'users/login', controller: 'users', action: 'login'

  put 'associations', controller: 'rock_structure_associations', action:'update'
  post 'associations', controller: 'rock_structure_associations', action:'create'
  get 'associations', controller: 'rock_structure_associations', action:'destroy'


  get 'statistics/photos_list',controller: 'statistics', action: 'photos_list'
  get 'statistics/sizes',controller: 'statistics', action: 'sizes'
  get 'statistics/altitudes', controller: 'statistics', action: 'altitudes'
  get 'statistics/stages_by_uf', controller: 'statistics', action: 'stages_by_uf'

  get 'projects/get_all_project_data', controller: 'projects', action: 'get_all_project_data'
end

app/models/outcrop.rb
class Outcrop < ApplicationRecord
  self.primary_key = 'uuid'
  belongs_to :stage
  has_many :outcrop_photos, dependent: :destroy
  has_many :structures, dependent: :destroy
  has_many :rocks, dependent: :destroy
  has_many :samples, dependent: :destroy
  has_many :rock_structure_associations, dependent: :destroy
  validates_presence_of :name
  validates_presence_of :latitude
  validates_presence_of :longitude
  validates_presence_of :stage_id

  before_create do
    self.persisted_time = DateTime.now.strftime('%Q')
  end

  before_create :generate_token

  protected

  def generate_token
    if self.uuid.nil?
      self.uuid = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Outcrop.exists?(uuid: random_token)
      end
    end
  end
end

app/controllers/outcrops_controller.rb
class OutcropsController < ApplicationController
  before_action :verify_auth_header
  before_action :set_outcrop, only: [:show, :edit, :update, :destroy]

  before_action :underscore_params!

  skip_before_filter :verify_authenticity_token

  def underscore_params!
    underscore_hash = -> (hash) do
      hash.transform_keys!(&:underscore)
      hash.each do |key, value|
        if value.is_a?(ActionController::Parameters)
          underscore_hash.call(value)
        elsif value.is_a?(Array)
          value.each do |item|
            next unless item.is_a?(ActionController::Parameters)
            underscore_hash.call(item)
          end
        end
      end
    end
    underscore_hash.call(params)
  end

  # GET /outcrops
  # GET /outcrops.json
  def index
    if params[:stage_id]
      @outcrops = Outcrop.where(stage_id: params[:stage_id])
                      .paginate(page: params[:page], per_page: params[:size])
                      .order(created_at: :desc)
                      .all
      render json: @outcrops

    else
      @outcrops = Outcrop.
          paginate(page: params[:page], per_page: params[:size])
                      .order(created_at: :desc)
                      .all
      render json: @outcrops
    end

  end

  def user_outcrops
    @outcrops = []
    if params[:user_id]
      @projects = Project.where(user_id: params[:user_id])
      for project in @projects
        @stages = project.stages
        for stage in @stages
          for outcrop in stage.outcrops
            @outcrops.push(outcrop)
          end
        end
      end
      render json: @outcrops
    else
      @outcrops = Outcrop.all
      render json: @outcrops
    end

  end

  # GET /outcrops/1
  # GET /outcrops/1.json
  def show
    render json: @outcrop
  end

  # GET /outcrops/new
  def new
    @outcrop = Outcrop.new
  end

  # GET /outcrops/1/edit
  def edit
  end

  # POST /outcrops
  # POST /outcrops.json
  def create
    @outcrop = Outcrop.new(outcrop_params)

    if @outcrop.save
      render json: @outcrop, status: :created
    else
      render json: @outcrop.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /outcrops/1
  # PATCH/PUT /outcrops/1.json
  def update
    if params[:updated_at].present?
      return render json: @outcrop, status: :ok if params[:updated_at].to_datetime < @outcrop.updated_at
    end

    if @outcrop.update(outcrop_params)
      render json: @outcrop, status: :ok
    else
      render json: @outcrop.errors, status: :unprocessable_entity
    end
  end

  # DELETE /outcrops/1
  # DELETE /outcrops/1.json
  def destroy
    if @outcrop.destroy
      render json: {message: 'Afloramento Excluido'}, status: :ok
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_outcrop
    @outcrop = Outcrop.find(params[:uuid])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def outcrop_params
    params.permit(:uuid, :altitude, :dateTime, :description, :latitude, :longitude, :name, :toponomy, :stage_id, :deleted_at, :updated_at)
  end
end

app/helpers/outcrops_helper.rb
module OutcropsHelper
end

app/views/outcrops/_form.html.erb
<%= form_for(outcrop) do |f| %>
  <% if outcrop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outcrop.errors.count, "error") %> prohibited this outcrop from being saved:</h2>

      <ul>
      <% outcrop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :altitude %>
    <%= f.text_field :altitude %>
  </div>

  <div class="field">
    <%= f.label :date_time %>
    <%= f.text_field :date_time %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :horizontal_datum %>
    <%= f.text_field :horizontal_datum %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :toponomy %>
    <%= f.text_field :toponomy %>
  </div>

  <div class="field">
    <%= f.label :stage_uuid %>
    <%= f.text_field :stage_uuid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outcrops/edit.html.erb
<h1>Editing Outcrop</h1>

<%= render 'form', outcrop: @outcrop %>

<%= link_to 'Show', @outcrop %> |
<%= link_to 'Back', outcrops_path %>

app/views/outcrops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Outcrops</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Altitude</th>
      <th>Date time</th>
      <th>Description</th>
      <th>Horizontal datum</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Name</th>
      <th>Toponomy</th>
      <th>Stage uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outcrops.each do |outcrop| %>
      <tr>
        <td><%= outcrop.uuid %></td>
        <td><%= outcrop.altitude %></td>
        <td><%= outcrop.date_time %></td>
        <td><%= outcrop.description %></td>
        <td><%= outcrop.horizontal_datum %></td>
        <td><%= outcrop.latitude %></td>
        <td><%= outcrop.longitude %></td>
        <td><%= outcrop.name %></td>
        <td><%= outcrop.toponomy %></td>
        <td><%= outcrop.stage_uuid %></td>
        <td><%= link_to 'Show', outcrop %></td>
        <td><%= link_to 'Edit', edit_outcrop_path(outcrop) %></td>
        <td><%= link_to 'Destroy', outcrop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outcrop', new_outcrop_path %>

app/views/outcrops/new.html.erb
<h1>New Outcrop</h1>

<%= render 'form', outcrop: @outcrop %>

<%= link_to 'Back', outcrops_path %>